/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SopsCategoryRouteImport } from './routes/sops.$category'
import { Route as AppVoiceGenRouteImport } from './routes/app.voice-gen'
import { Route as AppVoiceAccessRouteImport } from './routes/app.voice-access'
import { Route as AppTelegramRouteImport } from './routes/app.telegram'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSopsRouteImport } from './routes/app.sops'
import { Route as AppSecondBrainRouteImport } from './routes/app.second-brain'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppGrowthRouteImport } from './routes/app.growth'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppCustomsRouteImport } from './routes/app.customs'
import { Route as AppChattingRouteImport } from './routes/app.chatting'
import { Route as AppAccessRouteImport } from './routes/app.access'
import { Route as ApiPublicWebhookTasksRouteImport } from './routes/api/public/webhook.tasks'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SopsCategoryRoute = SopsCategoryRouteImport.update({
  id: '/sops/$category',
  path: '/sops/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceGenRoute = AppVoiceGenRouteImport.update({
  id: '/voice-gen',
  path: '/voice-gen',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceAccessRoute = AppVoiceAccessRouteImport.update({
  id: '/voice-access',
  path: '/voice-access',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSopsRoute = AppSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AppRoute,
} as any)
const AppSecondBrainRoute = AppSecondBrainRouteImport.update({
  id: '/second-brain',
  path: '/second-brain',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomsRoute = AppCustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => AppRoute,
} as any)
const AppChattingRoute = AppChattingRouteImport.update({
  id: '/chatting',
  path: '/chatting',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhookTasksRoute = ApiPublicWebhookTasksRouteImport.update({
  id: '/api/public/webhook/tasks',
  path: '/api/public/webhook/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/access': typeof AppAccessRoute
  '/app/chatting': typeof AppChattingRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/models': typeof AppModelsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/second-brain': typeof AppSecondBrainRoute
  '/app/sops': typeof AppSopsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/telegram': typeof AppTelegramRoute
  '/app/voice-access': typeof AppVoiceAccessRoute
  '/app/voice-gen': typeof AppVoiceGenRoute
  '/sops/$category': typeof SopsCategoryRoute
  '/app/': typeof AppIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhook/tasks': typeof ApiPublicWebhookTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/access': typeof AppAccessRoute
  '/app/chatting': typeof AppChattingRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/models': typeof AppModelsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/second-brain': typeof AppSecondBrainRoute
  '/app/sops': typeof AppSopsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/telegram': typeof AppTelegramRoute
  '/app/voice-access': typeof AppVoiceAccessRoute
  '/app/voice-gen': typeof AppVoiceGenRoute
  '/sops/$category': typeof SopsCategoryRoute
  '/app': typeof AppIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhook/tasks': typeof ApiPublicWebhookTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/access': typeof AppAccessRoute
  '/app/chatting': typeof AppChattingRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/models': typeof AppModelsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/second-brain': typeof AppSecondBrainRoute
  '/app/sops': typeof AppSopsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/telegram': typeof AppTelegramRoute
  '/app/voice-access': typeof AppVoiceAccessRoute
  '/app/voice-gen': typeof AppVoiceGenRoute
  '/sops/$category': typeof SopsCategoryRoute
  '/app/': typeof AppIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhook/tasks': typeof ApiPublicWebhookTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/access'
    | '/app/chatting'
    | '/app/customs'
    | '/app/finance'
    | '/app/goals'
    | '/app/growth'
    | '/app/models'
    | '/app/overview'
    | '/app/second-brain'
    | '/app/sops'
    | '/app/tasks'
    | '/app/team'
    | '/app/telegram'
    | '/app/voice-access'
    | '/app/voice-gen'
    | '/sops/$category'
    | '/app/'
    | '/api/public/telegram/webhook'
    | '/api/public/webhook/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/app/access'
    | '/app/chatting'
    | '/app/customs'
    | '/app/finance'
    | '/app/goals'
    | '/app/growth'
    | '/app/models'
    | '/app/overview'
    | '/app/second-brain'
    | '/app/sops'
    | '/app/tasks'
    | '/app/team'
    | '/app/telegram'
    | '/app/voice-access'
    | '/app/voice-gen'
    | '/sops/$category'
    | '/app'
    | '/api/public/telegram/webhook'
    | '/api/public/webhook/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/access'
    | '/app/chatting'
    | '/app/customs'
    | '/app/finance'
    | '/app/goals'
    | '/app/growth'
    | '/app/models'
    | '/app/overview'
    | '/app/second-brain'
    | '/app/sops'
    | '/app/tasks'
    | '/app/team'
    | '/app/telegram'
    | '/app/voice-access'
    | '/app/voice-gen'
    | '/sops/$category'
    | '/app/'
    | '/api/public/telegram/webhook'
    | '/api/public/webhook/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  SopsCategoryRoute: typeof SopsCategoryRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicWebhookTasksRoute: typeof ApiPublicWebhookTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sops/$category': {
      id: '/sops/$category'
      path: '/sops/$category'
      fullPath: '/sops/$category'
      preLoaderRoute: typeof SopsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/voice-gen': {
      id: '/app/voice-gen'
      path: '/voice-gen'
      fullPath: '/app/voice-gen'
      preLoaderRoute: typeof AppVoiceGenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice-access': {
      id: '/app/voice-access'
      path: '/voice-access'
      fullPath: '/app/voice-access'
      preLoaderRoute: typeof AppVoiceAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telegram': {
      id: '/app/telegram'
      path: '/telegram'
      fullPath: '/app/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sops': {
      id: '/app/sops'
      path: '/sops'
      fullPath: '/app/sops'
      preLoaderRoute: typeof AppSopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/second-brain': {
      id: '/app/second-brain'
      path: '/second-brain'
      fullPath: '/app/second-brain'
      preLoaderRoute: typeof AppSecondBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/growth': {
      id: '/app/growth'
      path: '/growth'
      fullPath: '/app/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customs': {
      id: '/app/customs'
      path: '/customs'
      fullPath: '/app/customs'
      preLoaderRoute: typeof AppCustomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chatting': {
      id: '/app/chatting'
      path: '/chatting'
      fullPath: '/app/chatting'
      preLoaderRoute: typeof AppChattingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/access': {
      id: '/app/access'
      path: '/access'
      fullPath: '/app/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhook/tasks': {
      id: '/api/public/webhook/tasks'
      path: '/api/public/webhook/tasks'
      fullPath: '/api/public/webhook/tasks'
      preLoaderRoute: typeof ApiPublicWebhookTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppChattingRoute: typeof AppChattingRoute
  AppCustomsRoute: typeof AppCustomsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppModelsRoute: typeof AppModelsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSecondBrainRoute: typeof AppSecondBrainRoute
  AppSopsRoute: typeof AppSopsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppVoiceAccessRoute: typeof AppVoiceAccessRoute
  AppVoiceGenRoute: typeof AppVoiceGenRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppChattingRoute: AppChattingRoute,
  AppCustomsRoute: AppCustomsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppModelsRoute: AppModelsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSecondBrainRoute: AppSecondBrainRoute,
  AppSopsRoute: AppSopsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppVoiceAccessRoute: AppVoiceAccessRoute,
  AppVoiceGenRoute: AppVoiceGenRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  SopsCategoryRoute: SopsCategoryRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicWebhookTasksRoute: ApiPublicWebhookTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
